In [1]:
import pandas as pd
import numpy as np

missing_values = ["n/a", "na", "--", "nan"]
data = pd.read_csv("./train.csv", na_values = missing_values)
#print(data.head())

/Users/markshaio/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3063: DtypeWarning: Columns (28) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [20]:
import sys
import numpy
numpy.set_printoptions(threshold=sys.maxsize)

#Get number of missing values for each feature
print(data.isnull().sum().to_string())

#See if there are any missing values
print(data.isnull().values.any())

#Get total missing values
print(data.isnull().sum().sum())

# print(data["AVProductsEnabled"].isnull().sum())
# data["AVProductsEnabled"].fillna(2.0,inplace=True)
# print(data["AVProductsEnabled"][:100].to_string())

#Fill missing values
#data["AVProductsEnabled"].fillna(10,inplace=True)

MachineIdentifier                                          0
ProductName                                                0
EngineVersion                                              0
AppVersion                                                 0
AvSigVersion                                               0
IsBeta                                                     0
RtpStateBitfield                                       32318
IsSxsPassiveMode                                           0
DefaultBrowsersIdentifier                            8488045
AVProductStatesIdentifier                              36221
AVProductsInstalled                                    36221
AVProductsEnabled                                          0
HasTpm                                                     0
CountryIdentifier                                          0
CityIdentifier                                        325409
OrganizationIdentifier                               2751518
GeoNameIdentifier       

In [20]:
data["IsProtected"].unique()
#ProductName: OK array(['win8defender', 'mse', 'mseprerelease', 'windowsintune', 'fep', 'scep'], dtype=object)
###AVProductStatesIdentifier : NO
###AVProductsEnabled: OK array([ 1.,  2.,  0.,  4., nan,  3.,  5.])
#HasTpm : OK array([1, 0])
#Platform: OK array(['windows10', 'windows7', 'windows8', 'windows2016'], dtype=object)
#Processor: OK array(['x64', 'arm64', 'x86'], dtype=object)
#OsVer: OK
#OsBuild: OK
#IsProtected: NO array([ 1.,  0., nan])
#PuaMode: NO array([nan, 'on', 'audit'], dtype=object) Potentially Unwanted Application Protection

"""
Potentially unwanted applications (PUA) are not considered viruses, malware, or other types of threats, 
but they might perform actions on endpoints which adversely affect endpoint performance or use.
PUA can also refer to an application that has a poor reputation, as assessed by Microsoft Defender ATP,
due to certain kinds of undesirable behavior.
"""

#SMode: NO array([ 0., nan,  1.])
#Firewall: NO array([ 1.,  0., nan])
###Census_OSArchitecture: OK array(['amd64', 'arm64', 'x86'], dtype=object) Possible duplicate to Processor
#Census_IsSecureBootEnabled: OK array([0, 1])
#Census_IsVirtualDevice: NO array([ 0., nan,  1.])
#Census_IsTouchEnabled: OK array([0, 1])

#Wdft_IsGamer: NO
#Wdft_RegionIdentifier: NO

#HasDetection: OK

array([ 1.,  0., nan])

In [55]:
data["ProductName"][:5]
data["Processor"].value_counts()

amd64    8105885
x86       815252
arm64        346
Name: Census_OSArchitecture, dtype: int64

In [57]:
data["Census_OSArchitecture"].value_counts()

amd64    8105885
x86       815252
arm64        346
Name: Census_OSArchitecture, dtype: int64

In [65]:
#print(data["ProductName"].isnull().sum())
# data["IsProtected"].fillna(2.,inplace=True)
# print(data["IsProtected"].isnull().sum())
data["Firewall"].unique()
data["Firewall"].fillna(2., inplace=True)
data["Firewall"].value_counts()

data["PuaMode"].fillna("unknown", inplace=True)
puamode_one_hot = pd.get_dummies(data["PuaMode"],prefix="PuaMode")
puamode_one_hot[:3]
#data["Firewall"][:3]
data["PuaMode"].value_counts()
# df = pd.DataFrame({'ProductName': ['win8defender', 'mse', 'mseprerelease', 'windowsintune', 'fep', 'scep']})

unknown    8919174
on            2307
audit            2
Name: PuaMode, dtype: int64

In [46]:
#Concatenates to dataframes, prodcut_name_one_hot and data
pd.concat([prodcut_name_one_hot, data], axis=1)

ProductName_fep  ProductName_mse  ProductName_mseprerelease  \
0                      0                0                          0   
1                      0                0                          0   
2                      0                0                          0   
3                      0                0                          0   
4                      0                0                          0   
...                  ...              ...                        ...   
8921478                0                0                          0   
8921479                0                0                          0   
8921480                0                0                          0   
8921481                0                0                          0   
8921482                0                0                          0   

         ProductName_scep  ProductName_win8defender  \
0                       0                         1   
1                       0                         1   
2                       0                         1   
3                       0                         1   
4                       0                         1   
...                   ...                       ...   
8921478                 0                         1   
8921479                 0                         1   
8921480                 0                         1   
8921481                 0                         1   
8921482                 0                         1   

         ProductName_windowsintune                 MachineIdentifier  \
0                                0  0000028988387b115f69f31a3bf04f09   
1                                0  000007535c3f730efa9ea0b7ef1bd645   
2                                0  000007905a28d863f6d0d597892cd692   
3                                0  00000b11598a75ea8ba1beea8459149f   
4                                0  000014a5f00daa18e76b81417eeb99fc   
...                            ...                               ...   
8921478                          0  ffffedfe8fcc46e6d36ab39953589fee   
8921479                          0  ffffef606490b2970873ec0a27ebd24b   
8921480                          0  fffff8a40070d2d8379bb7fa2ed2fa66   
8921481                          0  fffffbbaaf5969ae4b93e7f3f6d7132f   
8921482                          0  ffffff75ba4f33d938ccfdb148b8ea16   

          ProductName EngineVersion        AppVersion  ...  \
0        win8defender   1.1.15100.1   4.18.1807.18075  ...   
1        win8defender   1.1.14600.4      4.13.17134.1  ...   
2        win8defender   1.1.15100.1   4.18.1807.18075  ...   
3        win8defender   1.1.15100.1   4.18.1807.18075  ...   
4        win8defender   1.1.15100.1   4.18.1807.18075  ...   
...               ...           ...               ...  ...   
8921478  win8defender   1.1.15100.1   4.18.1807.18075  ...   
8921479  win8defender   1.1.13303.0     4.9.10586.672  ...   
8921480  win8defender   1.1.15200.1   4.18.1807.18075  ...   
8921481  win8defender   1.1.14901.4  4.16.17656.18052  ...   
8921482  win8defender   1.1.15200.1   4.18.1807.18075  ...   

        Census_FirmwareVersionIdentifier  Census_IsSecureBootEnabled  \
0                                36144.0                           0   
1                                57858.0                           0   
2                                52682.0                           0   
3                                20050.0                           0   
4                                19844.0                           0   
...                                  ...                         ...   
8921478                          63069.0                           1   
8921479                              NaN                           0   
8921480                          71061.0                           1   
8921481                          33142.0                           1   
8921482                          33084.0                           1   

        

# CLEAN DATA

In [71]:
"""
Might not be useful to train with PuaMode as a feature since data[PuaMode].value_counts returns
unknown    8919174
on            2307
audit            2
Name: PuaMode, dtype: int64
"""
#Cateogrical one hot encoding
prodcut_name_one_hot = pd.get_dummies(data["ProductName"],prefix='ProductName')
platform_one_hot = pd.get_dummies(data["Platform"],prefix="Platform")
processor_one_hot = pd.get_dummies(data["Processor"],prefix="Processor")

#Data filling
data["IsProtected"].fillna(2.,inplace=True)
data["Census_IsVirtualDevice"].fillna(2., inplace=True)
data["SMode"].fillna(2., inplace=True)
data["Firewall"].fillna(2., inplace=True)

#Data fill then one hot encoding for PuaMode
data["PuaMode"].fillna("unknown", inplace=True)
puamode_one_hot = pd.get_dummies(data["PuaMode"],prefix="PuaMode")

#Concatenate all dataframes
one_hot = [prodcut_name_one_hot,platform_one_hot,processor_one_hot,data]
nn_data = pd.concat(one_hot, axis=1)
nn_data

ProductName_fep  ProductName_mse  ProductName_mseprerelease  \
0                      0                0                          0   
1                      0                0                          0   
2                      0                0                          0   
3                      0                0                          0   
4                      0                0                          0   
...                  ...              ...                        ...   
8921478                0                0                          0   
8921479                0                0                          0   
8921480                0                0                          0   
8921481                0                0                          0   
8921482                0                0                          0   

         ProductName_scep  ProductName_win8defender  \
0                       0                         1   
1                       0                         1   
2                       0                         1   
3                       0                         1   
4                       0                         1   
...                   ...                       ...   
8921478                 0                         1   
8921479                 0                         1   
8921480                 0                         1   
8921481                 0                         1   
8921482                 0                         1   

         ProductName_windowsintune  Platform_windows10  Platform_windows2016  \
0                                0                   1                     0   
1                                0                   1                     0   
2                                0                   1                     0   
3                                0                   1                     0   
4                                0                   1                     0   
...                            ...                 ...                   ...   
8921478                          0                   1                     0   
8921479                          0                   1                     0   
8921480                          0                   1                     0   
8921481                          0                   1                     0   
8921482                          0                   1                     0   

         Platform_windows7  Platform_windows8  ...  \
0                        0                  0  ...   
1                        0                  0  ...   
2                        0                  0  ...   
3                        0                  0  ...   
4                        0                  0  ...   
...                    ...                ...  ...   
8921478                  0                  0  ...   
8921479                  0                  0  ...   
8921480                  0                  0  ...   
8921481                  0                  0  ...   
8921482                  0                  0  ...   

         Census_FirmwareVersionIdentifier  Census_IsSecureBootEnabled  \
0                                 36144.0                           0   
1                                 57858.0                           0   
2                                 52682.0                           0   
3                                 20050.0                           0   
4                                 19844.0                           0   
...                                   ...                         ...   
8921478                           63069.0                           1   
8921479                               NaN                           0   
8921480                           71061.0                           1   
8921481                           33142.0                           1   
8921482                           33084.0                           1 

In [159]:
input_columns = ["ProductName_fep","ProductName_mse","ProductName_mseprerelease","ProductName_scep","ProductName_win8defender","ProductName_windowsintune","ProductName_windowsintune","Platform_windows10","Platform_windows2016","Platform_windows7","Platform_windows8","Platform_windows2016","Processor_x64","Processor_arm64","Processor_x86","HasTpm","IsProtected","SMode","Firewall","Census_IsSecureBootEnabled","Census_IsVirtualDevice","Census_IsTouchEnabled","HasDetections"]
nn_input = nn_data[input_columns[:-1]]
nn_class = nn_data[input_columns[-1]]
nn_input.head(20)

ProductName_fep  ProductName_mse  ProductName_mseprerelease  \
0                 0                0                          0   
1                 0                0                          0   
2                 0                0                          0   
3                 0                0                          0   
4                 0                0                          0   
5                 0                0                          0   
6                 0                0                          0   
7                 0                0                          0   
8                 0                0                          0   
9                 0                0                          0   
10                0                0                          0   
11                0                0                          0   
12                0                0                          0   
13                0                0                          0   
14                0                0                          0   
15                0                0                          0   
16                0                1                          0   
17                0                0                          0   
18                0                0                          0   
19                0                0                          0   

    ProductName_scep  ProductName_win8defender  ProductName_windowsintune  \
0                  0                         1                          0   
1                  0                         1                          0   
2                  0                         1                          0   
3                  0                         1                          0   
4                  0                         1                          0   
5                  0                         1                          0   
6                  0                         1                          0   
7                  0                         1                          0   
8                  0                         1                          0   
9                  0                         1                          0   
10                 0                         1                          0   
11                 0                         1                          0   
12                 0                         1                          0   
13                 0                         1                          0   
14                 0                         1                          0   
15                 0                         1                          0   
16                 0                         0                          0   
17                 0                         1                          0   
18                 0                         1                          0   
19                 0                         1                          0   

    ProductName_windowsintune  Platform_windows10  Platform_windows2016  \
0                           0                   1                     0   
1                           0                   1                     0   
2                           0                   1                     0   
3                           0                   1                     0   
4                           0                   1                     0   
5                           0                   1                     0   
6                           0                   1                     0   
7                           0                   1                     0   
8                           0                   1                     0   
9                           0                   1                     0   
10                          0                   1                     0   
11                          0                   1                     0   
12 

# Neural Network Setup - Pytorch

In [172]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

class DQN(nn.Module):

    def __init__(self, first_layer_size):
        super().__init__()
        second_layer_size = round(first_layer_size / 3.75)
        third_layer_size = round(second_layer_size)
        self.fc1 = nn.Linear(in_features=first_layer_size, out_features=second_layer_size)
        self.fc2 = nn.Linear(in_features=second_layer_size, out_features=third_layer_size)
        self.out = nn.Linear(in_features=third_layer_size, out_features=1)

    def forward(self, t):
#         t = t.flatten(start_dim=1)
        t = F.relu(self.fc1(t))
        t = F.relu(self.fc2(t))
        t = torch.sigmoid(self.out(t))
        return t

#Instantiate the training neural network
train_nn = DQN(len(nn_input.columns))
lr = 0.01

>>> m = nn.Sigmoid()
>>> loss = nn.BCELoss()
>>> input = torch.randn(3, requires_grad=True)
>>> target = torch.empty(3).random_(2)
>>> output = loss(m(input), target)
>>> output.backward()

# NN Training

In [195]:
def stochastic(instance_count,train_nn):
    """
    Stochastic Learning
    
    Args:
    instance_count (int): The number of training instances
    train_nn (DQN): The training neural network
    """
    m = nn.Sigmoid()
    optimiser = optim.Adam(params=train_nn.parameters(), lr=lr)
    for i in range(instance_count):
        loss = nn.BCELoss()
        prediction = train_nn(torch.tensor(nn_input.values[i],dtype=torch.float32,requires_grad=True))
        target = torch.tensor(nn_class[i],dtype=torch.float32)
        loss_output = loss(prediction,target)
        optimiser.zero_grad()
        loss_output.backward()
        optimiser.step()
        print(loss_output)

stochastic(10,train_nn)
# print(torch.tensor(nn_input.values[4],dtype=torch.float32))
# print(train_nn(torch.tensor(nn_input.values[10],dtype=torch.float32)))

tensor(0.5733, grad_fn=<BinaryCrossEntropyBackward>)
tensor(0.5464, grad_fn=<BinaryCrossEntropyBackward>)
tensor(0.5183, grad_fn=<BinaryCrossEntropyBackward>)
tensor(0.9498, grad_fn=<BinaryCrossEntropyBackward>)
tensor(0.9581, grad_fn=<BinaryCrossEntropyBackward>)
tensor(0.9487, grad_fn=<BinaryCrossEntropyBackward>)
tensor(0.9325, grad_fn=<BinaryCrossEntropyBackward>)
tensor(0.5171, grad_fn=<BinaryCrossEntropyBackward>)
tensor(0.5262, grad_fn=<BinaryCrossEntropyBackward>)
tensor(0.8870, grad_fn=<BinaryCrossEntropyBackward>)


In [186]:
nn_class[:11]
torch.tensor(nn_class[0],dtype=torch.float32)

tensor(0.)

In [168]:
print(torch.tensor(nn_input.values[2],dtype=torch.float32))
print(torch.tensor(nn_input.values[3],dtype=torch.float32))
print(torch.tensor(nn_input.values[4],dtype=torch.float32))
print(train_nn(torch.tensor(nn_input.values[10],dtype=torch.float32)))

tensor([0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 1., 1., 0.,
        1., 0., 0., 0.])
tensor([0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 1., 1., 0.,
        1., 0., 0., 0.])
tensor([0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 1., 1., 0.,
        1., 0., 0., 0.])
tensor([0.5719], grad_fn=<SigmoidBackward>)


# TODO

In [ ]:
#1. Current features will have problems as for some instances, the same features result in different classifications.
#   Maybe include the country feature